apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-hostpath             
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-thanos-storegateway-0
  labels:
    type: local
spec:
  storageClassName: demo-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/thanos-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: storegateway
    app.kubernetes.io/instance: th
    app.kubernetes.io/name: thanos
  name: data-thanos-storegateway-0
spec:
  storageClassName: demo-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
